{
 "title": "Mattermost Performance Monitoring (Bonus Metrics)",
 "tags": [
  "mattermost",
  "mattermost-perf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Number of Successful Logins / Number of Login Attempts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Login Success Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_login_logins_total{instance=~\"$server\"}/(mattermost_login_logins_total{instance=~\"$server\"}+mattermost_login_logins_fail_total{instance=~\"$server\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_login_logins_total{instance=~\"$server\"})/(sum(mattermost_login_logins_total{instance=~\"$server\"})+sum(mattermost_login_logins_fail_total{instance=~\"$server\"}))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Number of Successful Logins per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_login_logins_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_login_logins_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Emails Sent per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_emails_sent_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_post_emails_sent_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Mobile Push Notifications Sent per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_pushes_sent_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_post_pushes_sent_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of File Attachments per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_file_attachments_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_post_file_attachments_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Search Queries for Posts per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_search_posts_searches_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_search_posts_searches_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean Search Query Time for Posts (in milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds (ms)" }
   ],
   "targets": [
    {
     "expr": "1000.0 * rate(mattermost_search_posts_searches_duration_seconds_sum{instance=~\"$server\"}[1m]) / rate(mattermost_search_posts_searches_duration_seconds_count{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Websocket Events per Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_websocket_event_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Number of Websocket Broadcasts per Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_websocket_broadcasts_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of API Requests per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_http_requests_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_http_requests_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Cluster Requests per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_cluster_cluster_requests_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_cluster_cluster_requests_total{instance=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Cluster Events per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_cluster_cluster_event_type_totals{instance=~\"$server\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration by Quantile (in seconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$server\"}",
     "legendFormat": "{{instance}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Number of Objects on the Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_memstats_heap_objects{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Etag Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "percentunit", "label": "Hit Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_cache_etag_hit_total{instance=~\"$server\"}/(mattermost_cache_etag_miss_total{instance=~\"$server\"} + mattermost_cache_etag_hit_total{instance=~\"$server\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Memory Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "percentunit", "label": "Hit Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_cache_mem_hit_total{instance=~\"$server\"}/(mattermost_cache_mem_miss_total{instance=~\"$server\"} + mattermost_cache_mem_hit_total{instance=~\"$server\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mean Etag Hit Rate (for each server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "percentunit", "label": "Hit Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_cache_etag_hit_total{instance=~\"$server\"}/(mattermost_cache_etag_miss_total{instance=~\"$server\"} + mattermost_cache_etag_hit_total{instance=~\"$server\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Mean Memory Cache Hit Rate (for each server)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "percentunit", "label": "Hit Rate" }
   ],
   "targets": [
    {
     "expr": "mattermost_cache_mem_hit_total{instance=~\"$server\"}/(mattermost_cache_mem_miss_total{instance=~\"$server\"} + mattermost_cache_mem_hit_total{instance=~\"$server\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resident Memory Size (in MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mattermost_process_resident_memory_bytes{instance=~\"$server\"}/1024/1024",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_process_resident_memory_bytes{instance=~\"$server\"}/1024/1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Virtual Memory Size (in MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mattermost_process_virtual_memory_bytes{instance=~\"$server\"}/1024/1024",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_process_virtual_memory_bytes{instance=~\"$server\"}/1024/1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_process_open_fds{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_process_open_fds{instance=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}