{
 "title": "Mattermost Calls - Performance Monitoring",
 "tags": [
  "mattermost",
  "mattermost-calls"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "calls", "label": "calls-instance", "query": { "query": "label_values(instance)" } },
   { "name": "rtcd", "label": "rtcd-instance", "query": { "query": "label_values(instance)" } },
   { "name": "rtcd_api_port", "query": "${VAR_RTCD_API_PORT}" },
   { "name": "calls_api_port", "query": "${VAR_CALLS_API_PORT}" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mattermost_plugin_calls_process_cpu_seconds_total{instance=~\"$calls:$calls_api_port\"}[2m])* 100) by (instance)",
     "legendFormat": "calls - {{ instance }}"
    },
    {
     "expr": "avg(irate(rtcd_process_cpu_seconds_total{instance=~\"$rtcd:$rtcd_api_port\"}[2m])* 100) by (instance)",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{instance=~\"$calls:$calls_api_port\"}) by (instance)",
     "legendFormat": "calls - {{ instance }}"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{instance=~\"$rtcd:$rtcd_api_port\"}) by (instance)",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "RTC Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mattermost_plugin_calls_rtc_sessions_total{instance=~\"$calls:$calls_api_port\"}) by (instance)",
     "legendFormat": "calls - {{ instance }}"
    },
    {
     "expr": "sum(rtcd_rtc_sessions_total{instance=~\"$rtcd:$rtcd_api_port\"}) by (instance)",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{instance=~\"$calls:$calls_api_port\"}) by (instance)",
     "legendFormat": "calls - {{ instance }}"
    },
    {
     "expr": "sum(go_goroutines{instance=~\"$rtcd:$rtcd_api_port\"}) by (instance)",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "WebSocket Events (calls plugin)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mattermost_plugin_calls_websocket_events_total{instance=~\"$calls:$calls_api_port\"}[2m])) by (instance, type)",
     "legendFormat": "calls - {{ type }}"
    }
   ]
  },
  {
   "title": "WebSocket Messages (rtcd)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(rtcd_ws_messages_total{instance=~\"$rtcd:$rtcd_api_port\"}[2m])) by (type, instance)",
     "legendFormat": "rtcd - {{type}} - {{ instance}}"
    }
   ]
  },
  {
   "title": "WebSocket Connections (rtcd)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rtcd_ws_connections_total{instance=~\"$rtcd:$rtcd_api_port\"}",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "RTC Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_calls_rtc_errors_total{instance=~\"$calls:$calls_api_port\"}[2m])) by (type, instance)",
     "legendFormat": "calls - {{ type }}"
    },
    {
     "expr": "sum(increase(rtcd_rtc_errors_total{instance=~\"$rtcd:$rtcd_api_port\"}[2m])) by (type, instance)",
     "legendFormat": "rtcd - {{ type }}"
    }
   ]
  },
  {
   "title": "RTC Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_calls_rtc_conn_states_total{instance=~\"$calls:$calls_api_port\"}[2m])) by (instance, type)",
     "legendFormat": "{{ instance }} - {{ type }}"
    },
    {
     "expr": "sum(increase(rtcd_rtc_conn_states_total{instance=~\"$rtcd:$rtcd_api_port\"}[2m])) by (instance, type)",
     "legendFormat": "rtcd - {{ instance }} - {{ type }}"
    }
   ]
  },
  {
   "title": "RTP Tracks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mattermost_plugin_calls_rtc_rtp_tracks_total{instance=~\"$calls:$calls_api_port\"}) by (instance, direction, type)",
     "legendFormat": "{{ instance }} - {{direction}} - {{type}}"
    },
    {
     "expr": "sum(rtcd_rtc_rtp_tracks_total{instance=~\"$rtcd:$rtcd_api_port\"}) by (instance, direction, type)",
     "legendFormat": "rtcd - {{ instance }} - {{direction}} - {{type}}"
    }
   ]
  },
  {
   "title": "Store Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(mattermost_plugin_calls_store_ops_total{instance=~\"$calls:$calls_api_port\"}[2m])) by (type, instance)",
     "legendFormat": "calls - {{ type }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Mutexes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_plugin_calls_cluster_mutex_grab_time_bucket{instance=~\"$calls:$calls_api_port\"}[2m])) by (group,le))",
     "legendFormat": "Grab time p99-{{group}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_plugin_calls_cluster_mutex_locked_time_bucket{instance=~\"$calls:$calls_api_port\"}[2m])) by (group,le))",
     "legendFormat": "Lock time p99-{{group}}"
    },
    {
     "expr": "sum(rate(mattermost_plugin_calls_cluster_mutex_grab_time_sum{instance=~\"$calls:$calls_api_port\"}[2m])) by (group) / sum(rate(mattermost_plugin_calls_cluster_mutex_grab_time_count{instance=~\"$calls:$calls_api_port\"}[2m])) by (group)",
     "legendFormat": "Grab time avg-{{group}}"
    },
    {
     "expr": "sum(rate(mattermost_plugin_calls_cluster_mutex_locked_time_sum{instance=~\"$calls:$calls_api_port\"}[2m])) by (group) / sum(rate(mattermost_plugin_calls_cluster_mutex_locked_time_count{instance=~\"$calls:$calls_api_port\"}[2m])) by (group)",
     "legendFormat": "Lock time avg-{{group}}"
    },
    {
     "expr": "sum(increase(mattermost_plugin_calls_cluster_mutex_lock_retries_total{instance=~\"$calls:$calls_api_port\"}[2m])) by (group)",
     "legendFormat": "Retries {{group}}"
    }
   ]
  },
  {
   "title": "Network RX/TX Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "(sum(rate(node_network_transmit_bytes_total{instance=~\"$rtcd:9100\"}[2m])) by (instance))*8",
     "legendFormat": "rtcd - TX Rate {{ instance }}"
    },
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{instance=~\"$rtcd:9100\"}[2m])) by (instance))*8",
     "legendFormat": "rtcd - RX Rate {{ instance }}"
    },
    {
     "expr": "(sum(rate(node_network_transmit_bytes_total{instance=~\"$calls:9100\"}[2m])) by (instance))*8",
     "legendFormat": "calls - TX Rate {{ instance }}"
    },
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{instance=~\"$calls:9100\"}[2m])) by (instance))*8",
     "legendFormat": "calls - RX Rate {{ instance }}"
    }
   ]
  },
  {
   "title": "TCP Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$rtcd:9100\"}",
     "legendFormat": "rtcd - {{ instance }} -  Connections - IPv4"
    },
    {
     "expr": "node_sockstat_TCP6_inuse{instance=~\"$rtcd:9100\"}",
     "legendFormat": "rtcd - {{ instance }} -  Connections - IPv6"
    },
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} -  Errors"
    },
    {
     "expr": "rate(node_netstat_TcpExt_TCPTimeouts{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} -  Timeouts"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} -  Retransmissions"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - In - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - Out - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - Errors - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{instance=~\"$calls:9100\"}[2m])",
     "legendFormat": "calls  - {{ instance }} - In - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams{instance=~\"$calls:9100\"}[2m])",
     "legendFormat": "calls - {{ instance }} - Out - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=~\"$calls:9100\"}[2m])",
     "legendFormat": "calls - {{ instance }} - Errors - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp6_InDatagrams{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - In - IPv6"
    },
    {
     "expr": "rate(node_netstat_Udp6_OutDatagrams{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - Out - IPv6"
    },
    {
     "expr": "rate(node_netstat_Udp6_InErrors{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - Errors - IPv6"
    }
   ]
  }
 ]
}