global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mattermost-monitor'

## Mattermost
scrape_configs:
  - job_name: 'mattermost'
    scrape_interval: 5s
    static_configs:
      - targets: ["mattermost:8067"]

## Caddy
  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2020']
