{
 "title": "Upstreams",
 "description": "Caddy Reverse Proxy Upstream Health",
 "tags": [
  "caddy",
  "caddy-upstream"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Reverse Proxy Upstream Healthy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mattermost:8065",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy{upstream=\"mattermost:8065\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promerheus:9090",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy{upstream=\"prometheus:9090\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana:3000",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy{upstream=\"grafana:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}